name: Example Workflow

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  revive:
    name: Run code quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Revive Action
        uses: morphy2k/revive-action@v2
        with:
          config: revive.toml

  test:
    name: run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: check out sources
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: fetch depencies
        run: go mod download

      - name: run tests
        run: go test -v ./...
